# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReferralApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReferralApp

  target 'ReferralAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReferralAppUITests' do
    # Pods for testing
  end

  # add the Firebase pod for Google Analytics
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'


# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

end
